language: java
jdk: oraclejdk8
sudo: false

notifications:
    email:
        - isaozturk@gmail.com

install: true

script:
- mvn clean package -DskipTests=false

# public repo on Travis CI
after_success:
  - bash <(curl -s https://codecov.io/bash)