language: java

jdk:
- oraclejdk8

os:
- linux

before_install:
    - pip install --user codecov    #Install codecov

install: true

script:
- mvn clean package -DskipTests=false

after_success:
  - bash <(curl -s https://codecov.io/bash)
