language: java
jdk: oraclejdk8
sudo: false

notifications:
    email:
        - isaozturk@gmail.com

install: true

script:
- mvn clean package -DskipTests=false

before_install:
    - pip install --user codecov    #Install codecov

after_success:
    - codecov                       #Run codecov
